networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:16
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
    volumes:
      - /docker/forgejo/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3001:3000'
      - '222:22'
