services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - TZ=${STACK_TIMEZONE}
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ${HOME}/homeassistant/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=${STACK_TIMEZONE}
      - DISABLE_JEMALLOC=true
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  swag:
    container_name: swag
    image: linuxserver/swag:3.0.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ${HOME}/swag/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL=${DUCK_DNS_EMAIL}
      - URL=${DUCK_DNS_URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - TZ=${STACK_TIMEZONE}
      - DUCKDNSTOKEN=${DUCK_DNS_TOKEN}
    ports:
      - "180:80"
      - "1443:443"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
#  wg-easy:
#    container_name: wg-easy
#    image: ghcr.io/wg-easy/wg-easy:14
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    sysctls:
#      - net.ipv4.ip_forward=1
#      - net.ipv4.conf.all.src_valid_mark=1
#    environment:
#      - TZ=${STACK_TIMEZONE}
#      - WG_HOST=${DUCK_DNS_URL}
#      - PASSWORD_HASH=${WG_EASY_PASSWORD_HASH}
#      - "WG_ALLOWED_IPS=${WG_EASY_ALLOWED_IPS}"
#    ports:
#      - "51820:51820/udp"
#      - "51821:51821/tcp"
#    restart: unless-stopped
#    volumes:
#      - ${HOME}/wg-easy/.wg-easy:/etc/wireguard
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    labels:
#      com.centurylinklabs.watchtower.enable: "true"
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${STACK_TIMEZONE}
      - APP_KEY=${SPEEDTEST_TRACKER_APP_KEY}
      - APP_TIMEZONE=${STACK_TIMEZONE}
      - DB_CONNECTION=sqlite
      - DISPLAY_TIMEZONE=${STACK_TIMEZONE}
      - SPEEDTEST_SCHEDULE=6 */2 * * *
      - CHART_DATETIME_FORMAT=j/m G:i
      - DATETIME_FORMAT=j M Y, G:i:s
    volumes:
      - ${HOME}/speedtest-tracker/config:/config
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"

# set trusted docker internal network
#networks:
#  default:
#    ipam:
#      config:
#        - subnet: ${DOCKER_INTERNAL_SUBNET}
